planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

#GlobalCostMap
global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: robot_base_link
      use_sim_time: True
      robot_radius: 0.15
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      #Static Layer
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        #Configuración de QoS para el tema del mapa
        map_subscribe_transient_local: True
        #Suscríbase a actualizaciones de mapas estáticos después de recibir primero.
        subscribe_to_updates: False
        #meters
        transform_tolerance: 0.1
        map_topic: /map

      #Inflation Layer
      inflation_layer:
        enabled: True
        #Radio para inflar el mapa de costos alrededor de obstáculos letales
        inflation_radius: 0.1
        #Factor de caída exponencial a lo largo del radio de inflación
        cost_scaling_factor: 3.0
        #Inflar celulas desconocidas como si fueran letales
        inflate_unknown: False
        inflate_around_unknown: False
        plugin: "nav2_costmap_2d::InflationLayer"
        always_send_full_costmap: True

      #Obstacle Layer
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        #Despeje cualquier celda ocupada bajo la huella del robot
        footprint_clearing_enabled: True
        #Altura máxima para agregar retorno a la cuadrícula de ocupación
        max_obstacle_height: 2.0
        #Enumeración del método para agregar datos al mapa de costos maestro, 
        #predeterminado al máximo
        combination_method: 1
        #espacio de nombres de las fuentes de datos.
        observation_sources: scan
        scan:
          topic: /scan
          sensor_frame: ""
          #Altura máxima para agregar un retorno a la cuadrícula de ocupación
          max_obstacle_height: 2.0
          #Cuánto tiempo almacenar mensajes en un búfer para agregarlos 
          #a costmap antes de eliminarlos
          observation_persistence: 0.0
          #Tasa esperada para obtener nuevos datos del sensor
          expected_update_rate: 0.0 
          #El tipo de datos de entrada, LaserScan o PointCloud2
          data_type: "LaserScan"
          #Si la fuente debe borrar el trazado de rayos en Costmap
          clearing: True
          #Si la fuente debe marcar en Costmap
          marking: True
          #Alcances min y max para marcar obstáculos en costmap
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          #Rango de alturas para agregar retorno a la cuadrícula de ocupación
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          #Borre las celdas ocupadas debajo de la huella del robot
          footprint_clearing_enabled: True
          #num para un método para agregar datos a Master Costmap, predeterminado al máximo
          combination_method: 1
          #¿Los retornos infinitos de los escáneres láser son medidas válidas para raycast?
          inf_is_valid: False

      # #Voxel Layer
      # voxel_layer:
      #     plugin: "nav2_costmap_2d::VoxelLayer"
      #     enabled: True
      #     #Despeje cualquier celda ocupada bajo la huella del robot
      #     footprint_clearing_enabled: true
      #     #Altura máxima para agregar retorno a la cuadrícula de ocupación
      #     max_obstacle_height: 2.0
      #     #Número de vóxeles altos a marcar, máximo 16
      #     z_voxels: 16
      #     #Por donde empezar a marcar Voxeles (m)
      #     origin_z: 0.0
      #     #Resolución de vóxeles en altura (m) 
      #     z_resolution: 0.05
      #     #Número mínimo de vóxeles vacíos en una columna para marcar
      #     #como desconocido en la cuadrícula de ocupación 2D.
      #     unknown_threshold: 15
      #     #Número mínimo de vóxeles en una columna para marcar como 
      #     #ocupados en la cuadrícula de ocupación 2D
      #     mark_threshold: 0
      #     #Enumeración del método para agregar datos al mapa de costos
      #     # maestro, predeterminado al máximo
      #     combination_method: 1
      #     #Ya sea para publicar la cuadrícula de vóxeles 3D para la
      #     # depuración, computacionalmente costoso
      #     publish_voxel_map: True
      #     observation_sources: pointcloud
      #     pointcloud:  # no frame set, uses frame from message
      #       topic: /intel_realsense_r200_depth/points
      #       sensor_frame: ""
      #       #Cuánto tiempo almacenar mensajes en un búfer para 
      #       #agregarlos a costmap antes de eliminarlos
      #       observation_persistence: 0.0
      #       expected_update_rate: 0.0
      #       data_type: "PointCloud2"
      #       max_obstacle_height: 2.0
      #       min_obstacle_height: 0.0
      #       #Rango de alturas para agregar retorno a la cuadrícula 
      #       #de ocupación          
      #       obstacle_max_range: 2.5
      #       obstacle_min_range: 0.0
      #       #Alcances min y max para marcar obstáculos en costmap
      #       raytrace_max_range: 3.0
      #       raytrace_min_range: 0.0
      #       #Son infinitas las devoluciones de los escáneres láser 
      #       #medidas válidas para raycast
      #       inf_is_valid: False
      #       #Si la fuente debe borrar el trazado de rayos en el mapa de costos
      #       clearing: True
      #       marking: True
